//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DongbuAPIClient_VC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DongbuAPIClientTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG1                     311
#define IDD_DLG_LOGIN                   311
#define IDD_DLG_ABLEQTY                 312
#define IDD_DLG_ORDER                   313
#define IDD_DLG_CHEGYUL                 314
#define IDD_DLG_JANGO                   314
#define IDD_DLG_CHE                     315
#define IDD_DLG_DEPOSIT                 316
#define IDD_DLG_RT                      317
#define IDD_DLG_FINDER                  318
#define IDD_DLG_SISE                    319
#define IDD_DLG_INVESTCHG               320
#define IDD_DLG_INVESTCME               320
#define IDD_DLG_INVEST                  321
#define IDD_DLG_INVEST_CHU              322
#define IDD_DIALOG5                     324
#define IDC_EDT_ID                      1000
#define IDC_EDT_CERT_PWD                1001
#define IDC_EDT_PWD                     1002
#define IDC_CHK_SHOWLOGIN               1003
#define IDD_DLG_AUTO_DUMMY_FORM         1003
#define IDC_CHK_MULTICONN               1004
#define IDC_EDT_NICK                    1005
#define IDC_BTN_LOGOUT                  1006
#define IDC_BTN_INIT                    1006
#define IDC_BTN_LOGIN                   1007
#define IDC_LIST                        1008
#define IDC_EDT_ACCOUNT                 1010
#define IDC_EDT_ACCTPWD                 1011
#define IDC_EDT_JONGMOK                 1012
#define IDC_EDT_DATE                    1012
#define IDC_EDT_QTY                     1014
#define IDC_CMB_PRICETYPE               1015
#define IDC_BTN_MESU                    1016
#define IDC_BTN_MEDO                    1017
#define IDC_EDT_ORGNO                   1018
#define IDC_BTN_MODIFY                  1019
#define IDC_BTN_CANCEL                  1020
#define IDC_BTN_ABLEQTY                 1021
#define IDC_RADIO_MESU                  1022
#define IDC_RADIO_MEDO                  1023
#define IDC_BTN_INQUERY                 1023
#define IDC_CHK_REALTIME                1024
#define IDC_BTN_INQUERY2                1024
#define IDC_BTN_ABLEQTY2                1024
#define IDC_CHK_HOGA                    1025
#define IDC_BTN_INQUERY_NEXT            1025
#define IDC_CHK_SISE                    1026
#define IDC_RADIO_BACK                  1031
#define IDC_RADIO_YUK                   1032
#define IDC_RADIO_COUNT                 1033
#define IDC_RADIO_ALL                   1034
#define IDC_RADIO_FOREIGN               1035
#define IDC_RADIO_ORGAN                 1036
#define IDC_CMB_INVEST                  1037
#define IDC_CMB_UPJONGCODE              1038
#define IDC_CMB_QTY                     1039
#define IDC_CMB_INVEST2                 1040
#define IDC_CMB_QTY2                    1042
#define IDC_EDIT2                       1042
#define IDC_TAB1                        1045
#define IDC_CHK_CREDITORDER             1046
#define IDD_BASE_FRM                    1122
#define IDD_DLG_AUTO_BASE_FRM           1122
#define IDD_DLG_AUTO_SETTING            1168
#define IDD_DLG_AUTO_SET_NORMAL         1169
#define IDD_DLG_AUTO_SET_DIV            1170
#define IDD_DLG_TEST                    1171
#define IDC_BTN_CONV                    2005
#define IDC_BTN_AVAILSELLVOL            2007
#define IDC_STC_ACNTNAME                2008
#define IDD_DIALOG2                     2009
#define IDC_BTN_JANGO                   2010
#define IDC_PIC_CODEINPUT               2011
#define IDC_BTN_REFRESH                 2013
#define IDC_STC_CODENAME                2014
#define IDC_STC_FO_CODENAME             2015
#define IDCT_RADIO_CASH                 2016
#define IDC_BTN_SET_ENV                 2017
#define IDC_PIC_FO_CODEINPUT            2018
#define IDCT_RADIO_CREDIT               2019
#define IDC_BTN_CAUTION                 2020
#define IDC_STC_CODENAME2               2021
#define IDE_ACCPASS                     2022
#define IDC_BTN_TIP                     2023
#define IDB_REG                         2024
#define IDC_BTN_WATCH_ALL               2025
#define IDB_ORDERLIST                   2026
#define IDC_BTN_CANCEL_ALL              2027
#define IDS_ACCNUM                      2028
#define IDC_BTN_SMS                     2029
#define IDS_INPUCODE                    2030
#define IDC_BTN_DELETE_ALL              2031
#define IDS_ITEMNAME                    2032
#define IDS_ITEMMARKET                  2033
#define IDCT_RADIO_SEMIAUTO             2034
#define IDCT_RADIO_AUTO                 2035
#define IDH_SMS                         2036
#define IDC_EXDATE                      2037
#define IDC_PRICETYPE                   2038
#define IDH_PRICETYPE                   2039
#define IDE_SELLVOLRATE                 2040
#define IDCT_SPIN_SELLVOLRATE           2041
#define IDE_SELLPRICE                   2042
#define IDCT_SPIN_SELLPRICE             2043
#define IDE_BUYVOL                      2044
#define IDCT_SPIN_BUYVOL                2045
#define IDE_BUYPRICE                    2046
#define IDCT_SPIN_BUYPRICE              2047
#define IDCT_TAB_ORDERCOND              2048
#define IDCT_TAB_ORDERTYPE              2049
#define IDCT_ORDERWND_NORMAL            2050
#define IDCT_ORDERWND_HOGADIV           2051
#define IDCT_ORDERWND_TIMEDIV           2052
#define IDCT_MAPLOAD                    2053
#define IDB_TEST                        2054
#define IDD_DIALOG3                     2055
#define IDCT_STATISTIC_CTRL             2057
#define IDE_RATE1                       2058
#define IDE_RATE2                       2059
#define IDE_RATE3                       2060
#define IDE_RATE4                       2061
#define IDE_RATE5                       2062
#define IDCT_SPIN_RATE1                 2063
#define IDCT_SPIN_RATE2                 2064
#define IDCT_SPIN_RATE3                 2065
#define IDCT_SPIN_RATE4                 2066
#define IDCT_SPIN_RATE5                 2067
#define IDE_VOLUME1                     2068
#define IDE_VOLUME2                     2069
#define IDE_VOLUME3                     2070
#define IDE_VOLUME4                     2071
#define IDE_VOLUME5                     2072
#define IDC_DIVSTD                      2073
#define IDE_DIVCNT                      2074
#define IDCT_SPIN_DIVCNT                2075
#define IDC_STDCOST                     2076
#define IDE_DIVUNIT                     2077
#define IDCT_SPIN_DIVUNIT               2078
#define IDB_DIVIDESET                   2079
#define IDCT_TAB_TYPE                   2080
#define IDS_ACCNAME                     2081
#define IDB_VOLCHECK                    2082
#define IDB_CONV                        2083
#define IDB_JANGO                       2084
#define IDB_SMS                         2085
#define IDB_WATCH                       2086
#define IDB_CLEAR                       2087
#define IDB_SEARCH                      2088
#define IDB_SMS_STATE                   2090
#define IDB_SMS_REG                     2091
#define IDB_LINK_ALIMI                  2092
#define IDC_SMSACCOUNT                  2093
#define IDCT_GRID_ORDLIST               2094
#define IDC_DIVWAY                      2095
#define IDD_DLG_MSGBOX                  2096
#define IDB_MSGBOX_YES                  2097
#define IDB_MSGBOX_NO                   2098
#define IDB_MSGBOX_SELL                 2099
#define IDB_MSGBOX_BUY                  2100
#define IDB_MSGBOX_OK                   2101
#define IDB_MSGBOX_CANCEL               2102
#define IDH_SELL                        2103
#define IDH_BUY                         2104
#define IDB_MSGBOX_OKSELLBUY            2105
#define IDS_ALERT                       2106
#define IDC_PRICEGB                     2107
#define IDR_HTML_HTMLATTENTIIONDLG      2109
#define IDCT_ATTENDSCROLLBAR            2110
#define IDB_LQVOLCHECK                  2111
#define IDB_TIP                         2112
#define IDD_DIALOG4                     2113
#define IDD_DLG_TIP                     2114
#define IDB_INIT                        2115
#define IDC_CREDITTYPE                  2116
#define IDCT_EXPIREDATE                 2117
#define IDE_EARNINGRATE                 2118
#define IDE_PREVENTLOSSRATE             2119
#define IDB_BITMAP1                     2120
#define IDB_EARNINGRATE                 2121
#define IDB_PREVENTLOSSRATE             2123
#define IDC_BTN_PERCENT                 2124
#define IDC_BTN_PRICE                   2125
#define IDC_STC_PRICE_TITLE             2126
#define IDC_BTN_MATCH_PRICE             2127
#define IDC_BTN_BASE_PRICE              2128
#define IDC_EDT_PRICE                   2129
#define IDC_STC_SUFFIX                  2130
#define IDC_BTN_SELL_VOL_PERCENT        2131
#define IDC_BTN_SELL_VOL_DIGIT          2132
#define IDC_BTN_BUY_VOL_AVAIL           2133
#define IDC_BTN_BUY_VOL_MAX             2134
#define IDC_BTN_BUY_VOL_TOT             2135
#define IDC_EDT_BUY_VOL_TOT             2136
#define IDC_BTN_BUY_VOL_TOT_APPLY       2137
#define IDC_BTN_DIV_APPLY               2138
#define IDC_BTN_INITSET                 2139
#define IDC_RDO_AUTO                    2140
#define IDC_RDO_SEMI                    2141
#define IDC_CHK_BEST_PRICE              2142
#define IDC_CHK_PROFIT                  2143
#define IDC_CHK_FIX_PROFIT              2144
#define IDC_CHK_FIX_LOSS                2145
#define IDC_EDT_COUNT                   2146
#define IDC_EDT_FIX_PROFIT1             2147
#define IDC_EDT_FIX_LOSS1               2148
#define IDC_EDT_FIX_PROFIT2             2149
#define IDC_EDT_FIX_PROFIT3             2150
#define IDC_EDT_FIX_LOSS2               2151
#define IDC_EDT_FIX_LOSS3               2152
#define IDC_TAB_RULE                    2153
#define IDC_CHK_LOSS                    2154
#define IDC_STC_DIV                     2155
#define IDC_CMB_INC                     2156
#define IDC_EDT_LOSS                    2157
#define IDC_CMB_BASE_PRICE              2158
#define IDC_EDT_PROFIT                  2159
#define IDC_CMB_DIR                     2160
#define IDC_CMB_VALID_DATE              2161
#define IDC_CMB_PRICE_TYPE              2162
#define IDC_EDT_RATE                    2163
#define IDC_CMB_SEL_PRICE               2164
#define IDC_CMB_PRICE_TYPE2             2165
#define IDC_CHECK2                      2166
#define IDC_CHK_APPLY_NEWITEM           2167
#define IDD_SETTING                     2168
#define IDD_SET_NORMAL                  2169
#define IDD_SET_DIV                     2170
#define IDC_COMBO1                      2171
#define IDC_CMB_CREDITGUBUN             2171
#define IDC_STTC_AVAILSELLVOL           2172
#define IDC_RDO_STK                     2173
#define IDC_RDO_ELW                     2174
#define IDC_STC_CODENAME_ELW            2175
#define IDC_PIC_CODEINPUT_ELW           2176
#define IDC_STC_ACNT_TITLE              2177
#define IDC_RDO_FO                      2178
#define IDC_RDO_ELW2                    2179
#define IDC_RDO_SFO                     2180
#define IDD_DLG_AGREEFORM               2181
#define IDC_RICHEDIT_CONTENTS           2182
#define IDC_CHECK_AGREE                 2183
#define IDC_STC_ACNT                    2186
#define IDC_PIC_CODENAME                2187
#define IDC_EDT_PASSWD                  2188
#define IDC_BTN_TICK                    2189
#define IDB_VOLCLEAR                    2190
#define IDC_BTN_BIDASKDLG               2191
#define IDC_SETTING_START               4000
#define IDC_SETNORMAL_START             4100
#define IDC_DTP_VALID_DATE              5004
#define IDC_STC_RATE                    5005
#define IDC_STC_SEL_PRICE               5006
#define IDC_STATIC1                     5011
#define IDC_STATIC2                     5012
#define IDC_STATIC3                     5013
#define IDC_STATIC4                     5014
#define IDC_STATIC5                     5015
#define IDC_STATIC6                     5016
#define IDC_STATIC7                     5017
#define IDC_BTN_LOG                     5018
#define ID_32771                        32771
#define ID_32773                        32773
#define ID_32775                        32775
#define ID_CME32776                     32776
#define ID_CME32777                     32777
#define ID_CME32778                     32778
#define ID_CME32779                     32779
#define ID_CME32780                     32780
#define ID_32781                        32781
#define IDM_LOGIN                       32782
#define ID_Menu                         32783
#define ID_Menu32784                    32784
#define IDM_CME_ORDER                   32785
#define IDM_CME_ABLEQTY                 32786
#define IDM_CME_JANGO                   32787
#define IDM_CME_CHE                     32788
#define IDM_CME_MICHE                   32789
#define IDM_CME_DEPOSIT                 32790
#define IDM_LOGOUT                      32791
#define ID_Menu32792                    32792
#define ID_RT_CME                       32793
#define IDM_CME_RT                      32794
#define IDM_FO_ORDER                    32795
#define IDM_FO_ABLEQTY                  32796
#define IDM_FO_CHE                      32797
#define IDM_FO_MICHE                    32798
#define IDM_FO_JANGO                    32799
#define IDM_FO_DEPOSIT                  32800
#define IDM_FO_RT                       32801
#define IDM_FUT_RT                      32802
#define IDM_OPT_RT                      32803
#define ID_32804                        32804
#define ID_32805                        32805
#define IDM_SK_ORDER                    32806
#define IDM_SK_ABLEQTY                  32807
#define IDM_SK_CHE                      32808
#define IDM_SK_MICHE                    32809
#define IDM_SK_JANGO                    32810
#define IDM_SK_DEPOSIT                  32811
#define IDM_SK_RT                       32812
#define IDM_SOPT_RT                     32813
#define IDM_SFO_RT                      32814
#define IDM_SK0_RT                      32815
#define IDM_SFO_ORDER                   32816
#define IDM_SFO_ABLEQTY                 32817
#define IDM_SFO_CHE                     32818
#define IDM_SFO_MICHE                   32819
#define IDM_SFO_JANGO                   32820
#define IDM_SFO_DEPOSIT                 32821
#define IDM_SFUT_RT                     32822
#define IDM_FUT_SYMBOLFINDER            32823
#define IDM_OPT_SYMBOLFINDER            32824
#define IDM_SK_SISE                     32825
#define IDM_SK_HOGA                     32826
#define IDM_FUT_SISE                    32827
#define IDM_FUT_HOGA                    32828
#define IDM_OPT_HOGA                    32829
#define IDM_SK_ACCOUNTLIST              32830
#define IDM_FO_ACCOUNTLIST              32831
#define ID_Menu32832                    32832
#define IDM_CME_INVESTCHG               32833
#define IDM_SK_INVESTTODAY              32834
#define ID_Menu32835                    32835
#define IDM_SK_INVEST                   32836
#define ID_32837                        32837
#define ID_Menu32838                    32838
#define ID_32839                        32839
#define ID_32840                        32840
#define IDM_SK_SVRORDER_SET             32841
#define IDM_SK_SVRORDER_SETALL          32842
#define ID_32844                        32844
#define ID_MY_TEST                      32845
#define IDM_MY_TEST                     32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        325
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
