
const UINT RMSG_GET_CONTROLHANDLE 		= ::RegisterWindowMessage(_T("RMSG_GET_CONTROLHANDLE"));
const UINT RMSG_GET_ACCOUNTNUM	  		= ::RegisterWindowMessage(_T("RMSG_GET_ACCOUNTNUM"));
//const UINT RMSG_GET_ITEMCODE	  		= ::RegisterWindowMessage(_T("RMSG_GET_ITEMCODE"));
const UINT RMSG_SET_FRAMEMSG	  		= ::RegisterWindowMessage(_T("RMSG_SET_FRAMEMSG"));
//const UINT RMSG_GET_ITEMCODEONMARKET	= ::RegisterWindowMessage(_T("RMSG_GET_ITEMCODEONMARKET"));
//const UINT RMSG_OPENSCREENWITHDATA		= ::RegisterWindowMessage(_T("RMSG_OPENSCREENWITHDATA"));
//const UINT RMSG_OPENSCREEN				= ::RegisterWindowMessage(_T("RMSG_OPENSCREEN"));
//const UINT RMSG_GET_SCREENNUM			= ::RegisterWindowMessage(_T("RMSG_GET_SCREENNUM"));
//const UINT RMSG_GET_SMSACCOUNTNUM	  	= ::RegisterWindowMessage(_T("RMSG_GET_SMSACCOUNTNUM"));

//const UINT RMSG_CHECK_PASSWORD			= ::RegisterWindowMessage(_T("RMSG_CHECK_PASSWORD"));
const UINT RMSG_BEGIN_WAITCURSOR		= ::RegisterWindowMessage(_T("RMSG_BEGIN_WAITCURSOR"));
const UINT RMSG_END_WAITCURSOR			= ::RegisterWindowMessage(_T("RMSG_END_WAITCURSOR"));


const UINT RMSG_RECV_77080			= ::RegisterWindowMessage(_T("RMSG_RECV_77080"));
const UINT RMSG_SET_FOCUS			= ::RegisterWindowMessage(_T("RMSG_SET_FOCUS"));
const UINT RMSG_REQ_AGREE_FLAG		= ::RegisterWindowMessage(_T("RMSG_REQ_AGREE_FLAG"));
//const UINT RMSG_CHANGE_CURSOR		= ::RegisterWindowMessage(_T("RMSG_CHANGE_CURSOR"));
const UINT RMSG_SET_TR_RESULT_MSG	= ::RegisterWindowMessage(_T("RMSG_SET_TR_RESULT_MSG"));
const UINT RMSG_REQ_ALLFO_VOL		= ::RegisterWindowMessage(_T("RMSG_REQ_ALLFO_VOL"));

//### Condition Map Message Define ###
#define WM_NOTIFY_MAPLOAD						WM_USER + 240
#define NM_MAPLOAD_UPDATE						1
#define NM_MAPLOAD_OK							2
#define NM_MAPLOAD_CLOSE						3
#define CHANGE_EXP								99


#define NM_CHECK_CONDITION		5	
#define NM_SELECT_CONDITION		6

#define UMSG_GET_BUY_VOLUME		6
#define UMSG_GET_SELL_VOLUME	7
#define UMSG_SENDTR_JANGO		31


//#define UMSG_SENDTR_PHONENUM	WM_USER + 33
//#define UMSG_SENDTR_SMS			WM_USER + 34
//#define UMSG_GETMARKETTYPE		WM_USER + 35
#define UMSG_GETCURMARKETTAB	WM_USER + 36
//#define UMSG_SETITEMCODE		WM_USER + 37

#define UMSG_REGCONDITION		WM_USER + 40
#define UMSG_MESSAGEBOX			WM_USER + 41
#define UMSG_CHECKWATCHING		WM_USER + 42
//#define UMSG_CHECKINVESTORINFO	WM_USER + 43

#define UMSG_CHECKINVESTINFO	WM_USER + 45
#define UMSG_SETTYPE_VOLCHECK	WM_USER + 47
#define UMSG_TR_STOCKHOGA		WM_USER + 48
//#define UMSG_TR_FUTOPT			WM_USER + 49
//#define UMSG_ELWDLG				WM_USER + 50

//#define UMSG_CHECKPASSEDITBOX	WM_USER + 52
#define UMSG_GETUSECREDIT		WM_USER + 53
//#define UMSG_SVRATTENTIONVERIFY	WM_USER + 54

#define UMSG_GET_ORDAUTOFLAG	WM_USER + 56
#define UMSG_GET_MMTYPE			WM_USER + 57
#define UMSG_GET_GRID_LOSSANDPROFIT		WM_USER + 58 
//#define UMSG_TR_ELW				WM_USER + 59 //[0000549]ELWÈ£°¡ SJ_KIM(20110923)

#define UMSG_SET_RESULT_MSG		WM_USER + 60 
#define UMSG_GET_IP				WM_USER + 61

#define UMSG_GET_TYPE_TAB_CUR_SEL		WM_USER + 63
#define UMSG_GET_RDO_CASH_CREDIT	 WM_USER + 64
#define UMSG_IS_SELL_TAB_SELECTED	 WM_USER + 65

#define UMSG_CHECK_MP		WM_USER + 68


#define WM_NOTIFY_GRID					WM_USER + 241
#define NM_GRID_CLK						WM_USER + 242
#define NM_GRID_CLK_MODIFYBTN			WM_USER + 243
#define NM_GRID_CLK_BUY_DELBTN			WM_USER + 244
#define NM_GRID_CLK_SELL_DELBTN			WM_USER + 245
#define NM_GRID_CLK_SHARECODE			WM_USER + 246

#define NM_GRID_JANGO_CREDIT			WM_USER + 248
#define NM_GRID_TOGGLE_WATCHING			WM_USER + 249




